# Generated by Django 5.0.6 on 2024-05-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='asistencias',
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
