# Generated by Django 5.0.6 on 2024-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimapp', '0002_remove_jugador_asistencias_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
