# Generated by Django 5.0.6 on 2024-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimapp', '0003_alter_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ano_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
