# Generated by Django 5.0.6 on 2024-06-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimapp', '0004_alter_equipo_ano_fundacion_alter_equipo_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='competicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futsimapp.competicion'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
